### ISSUE TITLE
App occasionally crashes after alarm is dismissed

### ISSUE THREAD

**Issue by smichel17** [trikita/talalarmo#31]
I finally got a log of this. I'm using the version from #26 and I haven't investigated whether this is related to my changes or not; I just wanted to leave this here before I lose it.

```
E AndroidRuntime: Process: trikita.talalarmo.debug, PID: 29457
E AndroidRuntime: java.lang.IllegalStateException
E AndroidRuntime:        at android.media.MediaPlayer._setVolume(Native Method)
E AndroidRuntime:        at android.media.MediaPlayer.playerSetVolume(MediaPlayer.java:2357)
E AndroidRuntime:        at android.media.PlayerBase.baseSetVolume(PlayerBase.java:111)
E AndroidRuntime:        at android.media.MediaPlayer.setVolume(MediaPlayer.java:2352)
E AndroidRuntime:        at trikita.talalarmo.alarm.AlarmService$2.run(AlarmService.java:54)
E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by xeruf** [comment]
what does "on dismiss" mean? Is it related to #19/#29?

**Comment by smichel17** [comment]
Alarm goes off, tap (or in my case, hold) to dismiss, alarm is successfully dismissed and a crash dialog appears. It hasn't happened much recently so I don't remember exactly which dialog.

**Comment by xeruf** [comment]
okay, so this is a different bug, maybe you can rename it to "App sometimes crashes on Alarm dismiss" to make that clear

**Comment by smichel17** [comment]
I thought it was clear, but ok

**Comment by xeruf** [comment]
Well, "dismiss" could also refer to dismissing the App (i.e. terminating it from the task manager)

**Comment by smichel17** [comment]
I finally have a log of this. Here's the crash itself; I can sort out the earlier talalarmo logs if needed but I don't think it will be…
```
01-06 06:30:31.552 11021 11044 E AndroidRuntime: FATAL EXCEPTION: alarm_service
01-06 06:30:31.552 11021 11044 E AndroidRuntime: Process: trikita.talalarmo.debug, PID: 11021
01-06 06:30:31.552 11021 11044 E AndroidRuntime: java.lang.IllegalStateException
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.media.MediaPlayer._setVolume(Native Method)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.media.MediaPlayer.playerSetVolume(MediaPlayer.java:2357)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.media.PlayerBase.baseSetVolume(PlayerBase.java:111)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.media.MediaPlayer.setVolume(MediaPlayer.java:2352)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at trikita.talalarmo.alarm.AlarmService$2.run(AlarmService.java:54)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-06 06:30:31.552 11021 11044 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
```
